### ISSUE TITLE
[Feature Request] CSS或内联样式style中url()的替换

### ISSUE THREAD

**Issue by Naccl** [PipecraftNet/jsdelivr-auto-fallback#2]
比如

```html
<div style="background-image: url("https://cdn.jsdelivr.net/something");"></div>
```

```css
image {
  background-image: url("https://cdn.jsdelivr.net/something");
}
```
